image:
  - Visual Studio 2017
environment:
  matrix:
    - PATH: C:\Python36-x64;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
    - PATH: C:\Python37-x64;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  # matrix:
    # - VSVER: Visual Studio 14 2015
    # - VSVER: Visual Studio 14 2015 Win64

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  
clone_folder: C:\projects\blond_common
platform: 
  - x86

configuration:
  # - Debug
  - Release

# install:
  # - set PATH=C:\Python36-x64;%PATH%
  # - set PATH=C:\Miniconda36-x64;%PATH%
  
before_build:
  # - git submodule update --init --recursive
  - PATH
  - python --version
  # - conda --version 
  - gcc --version
  - python -m pip install --upgrade pip setuptools wheel pytest 
  - python -m pip install -r requirements.txt
  # - pip install coveralls pytest parameterized


build_script:
  # - python setup.py install
  - DIR
  # - SET PYTHONPATH=C:\projects;%PYTHONPATH%
  # - SET PYTHONPATH=%PYTHONPATH%;..\

test_script:
  - python -m pytest -v -k "unittests and test and py" __TESTS\unittests\